#!/usr/bin/env bash
# setup.sh - Setup Auto Bet Plinko Stake.com
# Jalankan: bash setup.sh

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC}   $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
die()     { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

echo ""
echo "======================================================"
echo "   Plinko Auto-Bet -- Setup Script"
echo "======================================================"
echo ""

# ── 1. Cek Python 3 ──────────────────────────────────────
info "Memeriksa Python 3..."
if ! command -v python3 >/dev/null 2>&1; then
    warn "Python 3 tidak ditemukan. Mencoba install..."
    if command -v apt-get >/dev/null 2>&1; then
        sudo apt-get update -qq && sudo apt-get install -y python3 python3-pip
    elif command -v dnf >/dev/null 2>&1; then
        sudo dnf install -y python3 python3-pip
    elif command -v yum >/dev/null 2>&1; then
        sudo yum install -y python3 python3-pip
    else
        die "Tidak bisa install Python otomatis. Install manual dulu."
    fi
fi
success "Ditemukan: $(python3 --version 2>&1)"

# ── 2. Install dependensi ─────────────────────────────────
info "Menginstall dependensi Python..."
pip3 install --quiet --upgrade pip
pip3 install --quiet -r requirements.txt
success "Dependensi terinstall."

# ── 3. Input token ────────────────────────────────────────
ENV_FILE=".env"
OLD_TOKEN=""
if [ -f "$ENV_FILE" ]; then
    OLD_TOKEN=$(grep -E '^STAKE_API_TOKEN=' "$ENV_FILE" | cut -d= -f2- | tr -d "\"'" || true)
fi

echo ""
echo "------------------------------------------------------"
echo "  Cara dapat token:"
echo "  Buka Stake.com → login → F12 → tab Network"
echo "  → klik request ke _api/graphql → Request Headers"
echo "  → salin nilai x-access-token"
echo "------------------------------------------------------"
echo ""

while true; do
    if [ -n "$OLD_TOKEN" ]; then
        read -rp "  STAKE_API_TOKEN [Enter = pakai token lama]: " STAKE_API_TOKEN
        STAKE_API_TOKEN="${STAKE_API_TOKEN:-$OLD_TOKEN}"
    else
        read -rp "  STAKE_API_TOKEN: " STAKE_API_TOKEN
    fi
    if [ -n "$STAKE_API_TOKEN" ]; then break; fi
    warn "Token tidak boleh kosong."
done

# ── 4. Tulis .env ─────────────────────────────────────────
{
    echo "# Auto-generated by setup.sh -- $(date)"
    echo "# Untuk ubah pengaturan lain, edit file ini langsung."
    echo ""
    echo "STAKE_API_TOKEN=${STAKE_API_TOKEN}"
    echo ""
    echo "# === Pengaturan Game ==="
    echo "RISK=LOW"
    echo "ROWS=8"
    echo "BET_AMOUNT=500"
    echo "CURRENCY=IDR"
    echo ""
    echo "# === Strategi (FLAT / ANTI_MARTINGALE) ==="
    echo "STRATEGY=FLAT"
    echo "BET_MULTIPLIER=2"
    echo "WIN_STREAK_CAP=3"
    echo "MAX_BET=0"
    echo ""
    echo "# === Kontrol Bot ==="
    echo "BASE_DELAY_MS=200"
    echo "STOP_LOSS=10000"
    echo "TAKE_PROFIT=0"
    echo "TAKE_PROFIT_DELAY_SEC=30"
    echo "WAGER_TARGET=0"
    echo "MAX_CONSECUTIVE_ERRORS=5"
    echo "MAX_RATE_LIMIT_RETRIES=10"
} > "$ENV_FILE"

success "File .env berhasil ditulis."

# Pastikan .env tidak masuk git
if [ -f ".gitignore" ]; then
    if ! grep -qxF '.env' .gitignore; then
        echo '.env' >> .gitignore
    fi
else
    echo '.env' > .gitignore
fi

# ── 5. Selesai ────────────────────────────────────────────
echo ""
echo "======================================================"
success "Setup selesai!"
echo ""
echo "  Jalankan bot:"
echo "    python3 main.py"
echo ""
echo "  Background (VPS):"
echo "    nohup python3 main.py > plinko.log 2>&1 &"
echo "    tail -f plinko.log"
echo ""
echo "  Stop bot:"
echo "    kill \$(pgrep -f 'python3 main.py')"
echo ""
echo "  Edit pengaturan lain (bet, stop loss, dll):"
echo "    nano .env"
echo "======================================================"
