#!/usr/bin/env bash
# setup.sh - Setup Auto Bet Plinko Stake.com
# Jalankan: bash setup.sh

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC}   $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
die()     { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

echo ""
echo "======================================================"
echo "   Plinko Auto-Bet -- Setup Script"
echo "======================================================"
echo ""

# ── 1. Cek Python 3 ──────────────────────────────────────
info "Memeriksa Python 3..."
if ! command -v python3 >/dev/null 2>&1; then
    warn "Python 3 tidak ditemukan. Mencoba install..."
    if command -v apt-get >/dev/null 2>&1; then
        sudo apt-get update -qq && sudo apt-get install -y python3 python3-pip
    elif command -v dnf >/dev/null 2>&1; then
        sudo dnf install -y python3 python3-pip
    elif command -v yum >/dev/null 2>&1; then
        sudo yum install -y python3 python3-pip
    else
        die "Tidak bisa install Python otomatis. Install manual dulu."
    fi
fi
success "Ditemukan: $(python3 --version 2>&1)"

# Validasi versi minimum Python 3.8
_py_ver=$(python3 -c "import sys; print(sys.version_info >= (3,8))" 2>/dev/null)
if [ "$_py_ver" != "True" ]; then
    die "Python 3.8+ diperlukan. Versi kamu: $(python3 --version 2>&1)\n   Upgrade: sudo apt install python3.8"
fi

# ── 2. Install dependensi ─────────────────────────────────
# BUG FIX: pakai 'python3 -m pip' bukan 'pip3' agar lebih portabel
# (pip3 tidak selalu ada meski python3 sudah terinstall)
# BUG FIX: upgrade pip bisa gagal di sistem yang pip-nya dikelola OS
# (Debian/Ubuntu PEP 668) — jangan biarkan kegagalan ini menghentikan setup
info "Menginstall dependensi Python..."
python3 -m pip install --quiet --upgrade pip 2>/dev/null || \
    warn "Tidak bisa upgrade pip (diabaikan, lanjut install dependensi)"

# Coba install biasa dulu; jika gagal karena sistem yang dikelola OS,
# gunakan --user agar tidak perlu root dan tidak merusak paket sistem
if ! python3 -m pip install --quiet -r requirements.txt 2>/dev/null; then
    info "Mencoba install dengan --user (sistem managed)..."
    python3 -m pip install --quiet --user -r requirements.txt || \
        die "Gagal install dependensi. Coba jalankan manual: python3 -m pip install -r requirements.txt"
fi
success "Dependensi terinstall."

# ── 3. Input token ────────────────────────────────────────
ENV_FILE=".env"
OLD_TOKEN=""
if [ -f "$ENV_FILE" ]; then
    OLD_TOKEN=$(grep -E '^STAKE_API_TOKEN=' "$ENV_FILE" | cut -d= -f2- | tr -d "\"'" | xargs || true)
fi

echo ""
echo "------------------------------------------------------"
echo "  Cara dapat token:"
echo "  Buka Stake.com → login → F12 → tab Network"
echo "  → klik request ke _api/graphql → Request Headers"
echo "  → salin nilai x-access-token"
echo "------------------------------------------------------"
echo ""

while true; do
    if [ -n "$OLD_TOKEN" ]; then
        read -rp "  STAKE_API_TOKEN [Enter = pakai token lama]: " STAKE_API_TOKEN
        STAKE_API_TOKEN="${STAKE_API_TOKEN:-$OLD_TOKEN}"
    else
        read -rp "  STAKE_API_TOKEN: " STAKE_API_TOKEN
    fi
    if [ -n "$STAKE_API_TOKEN" ]; then break; fi
    warn "Token tidak boleh kosong."
done

# ── 4. Tulis .env ─────────────────────────────────────────
# BUG FIX: .env hanya menyimpan token.
# Settings game (RISK, ROWS, BET_AMOUNT, dll) ADA di config_profit.env
# dan config_wager.env — jika .env juga menyimpan settings itu,
# nilainya akan OVERRIDE preset karena .env di-load dengan prioritas lebih tinggi.
{
    echo "# Auto-generated by setup.sh -- $(date)"
    echo "# File ini hanya menyimpan token."
    echo "# Pengaturan game ada di config_profit.env dan config_wager.env"
    echo ""
    echo "STAKE_API_TOKEN=${STAKE_API_TOKEN}"
} > "$ENV_FILE"

success "File .env berhasil ditulis."

# Pastikan .env tidak masuk git
if [ -f ".gitignore" ]; then
    if ! grep -qxF '.env' .gitignore; then
        echo '.env' >> .gitignore
    fi
else
    echo '.env' > .gitignore
fi

# ── 5. Selesai ────────────────────────────────────────────
echo ""
echo "======================================================"
success "Setup selesai!"
echo ""
echo "  Jalankan bot (menu interaktif):"
echo "    python3 main.py"
echo ""
echo "  Jalankan langsung tanpa menu:"
echo "    python3 main.py profit --rows 14"
echo "    python3 main.py profit --rows 16"
echo "    python3 main.py wager"
echo ""
echo "  Background / VPS (nohup) — WAJIB sertakan mode:"
echo "    nohup python3 main.py profit --rows 14 > plinko.log 2>&1 &"
echo "    nohup python3 main.py wager > plinko.log 2>&1 &"
echo "    tail -f plinko.log"
echo ""
echo "  Stop bot:"
echo "    kill \$(pgrep -f 'python3 main.py')"
echo ""
echo "  Ubah token (jalankan ulang setup):"
echo "    bash setup.sh"
echo "======================================================"
